# Generated by Django 2.0.1 on 2018-05-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laTitle', models.CharField(max_length=10)),
                ('laMoney', models.CharField(max_length=10)),
                ('laPosition', models.CharField(max_length=20)),
                ('laType', models.CharField(max_length=30)),
                ('laReleaseTime', models.CharField(max_length=20)),
            ],
        ),
    ]
